#!/bin/sh

# Created at: 2023-11-19_1023
# By: penguins_eggs v. 9.6.12
# ==> Perri's Brewery edition <== 

xorriso -as mkisofs -J -joliet-long -l -iso-level 3 -isohybrid-mbr /usr/lib/syslinux/bios/isohdpfx.bin -partition_offset 16 -V _Wexium_ -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e boot/grub/efiboot.img -isohybrid-gpt-basdat -no-emul-boot -o /home/eggs/mnt/Wexium_Wexium__amd64_2023-11-19_1023.iso /home/eggs/mnt/iso/
